.travis.yml, .tx/config, CHANGES.rst, CONTRIBUTING.rst, INSTALL.rst, MANIFEST.in, README.rst, RELEASE-NOTES.rst, babel.ini, docs/api.rst, docs/authors.rst, docs/conf.py, docs/configuration.rst, docs/contributing.rst, docs/examplesapp.rst, docs/index.rst, docs/installation.rst, docs/requirements.txt, docs/usage.rst, invenio_stats/cli.py, invenio_stats/manager.py, invenio_stats/version.py, invenio_stats/views.py, pytest.ini, run-tests.sh, setup.py, tests/conftest.py
=> global: cookiecutter sync

.travis.yml, invenio_stats/contrib/events.py, invenio_stats/tasks.py, requirements-devel.txt, setup.py, tests/conftest.py, tests/test_invenio_stats.py, tests/test_tasks.py
=> tests: testing batch events

invenio_stats/contrib/aggregations/aggr-file-download/aggr-file-download-v1.json, invenio_stats/contrib/aggregations/aggr-record-view/aggr-record-view-v1.json, invenio_stats/tasks.py, tests/conftest.py, tests/test_invenio_stats.py
* ADDS index interval parameter to support
e.g. monthly aggregations and yearly indices
=> global: decoupling aggregation & index intervals

.travis.yml, invenio_stats/contrib/aggregations/aggr-file-download/aggr-file-download-v1.json, invenio_stats/contrib/aggregations/aggr-record-view/aggr-record-view-v1.json, invenio_stats/contrib/file-download/file-download-v1.json, invenio_stats/contrib/record-view/record-view-v1.json, invenio_stats/receivers.py, invenio_stats/tasks.py, tests/conftest.py, tests/test_invenio_stats.py
* ADDS test for date range aggregations
* FIXES conftest fixture indexing mock events
=> tests: date range test

invenio_stats/aggregations.py, invenio_stats/errors.py, tests/conftest.py, tests/test_aggregations.py
* ADDS splitting of intervals when aggregating to
handle large number of documents.
=> global: aggregation partitioning

invenio_stats/aggregations.py, tests/conftest.py, tests/test_aggregations.py
* Adds a query_modifiers parameter to StatAggregator and create a
filter_robots query modifier.
=> global: filter robots in StatAggregator

CHANGES.rst, RELEASE-NOTES.rst, invenio_stats/version.py
=> release: v1.0.0a2

invenio_stats/views.py
* ADD post method in the API for statistics requests
coming from the UI.
=> views: addition of post method

invenio_stats/views.py
* ADD exception handling for when stats indices
have not yet been created in ES
(closes https://github.com/inveniosoftware/invenio-stats/issues/24)
=>  views: index doesn't exist fix

examples/app.py, invenio_stats/views.py
=> queries: moving get to post

CHANGES.rst, RELEASE-NOTES.rst, invenio_stats/version.py
=> release: v1.0.0a3

tests/conftest.py
* ADD generator for timestamps to register events in
different time windows
=> tests: unique timestamping

invenio_stats/config.py, invenio_stats/ext.py, invenio_stats/receivers.py, tests/conftest.py
* Adds the possibility to override event, aggregation and queries
configuration.
=> global: Enable config override

CHANGES.rst, RELEASE-NOTES.rst, invenio_stats/version.py
=> release: v1.0.0a4

CHANGES.rst, RELEASE-NOTES.rst, invenio_stats/processors.py, invenio_stats/version.py
=> release: v1.0.0a5

invenio_stats/aggregations.py, tests/conftest.py, tests/test_aggregations.py
* Fixes the errors raised when an aggregation runs without any
indexed events.
=> global: fix aggregation when there are no events

CHANGES.rst, RELEASE-NOTES.rst, invenio_stats/version.py
=> release: v1.0.0a6

CHANGES.rst, RELEASE-NOTES.rst, invenio_stats/version.py
=> release: v1.0.0a7

.editorconfig, CHANGES.rst, RELEASE-NOTES.rst, invenio_stats/version.py, setup.py
=> release: v1.0.0a8

README.rst
=> docs: fix url in README.rst

.travis.yml, invenio_stats/aggregations.py, invenio_stats/cli.py, invenio_stats/contrib/aggregations/aggr_file_download/v2/aggr-file-download-v1.json, invenio_stats/contrib/aggregations/aggr_file_download/v5/aggr-file-download-v1.json, invenio_stats/contrib/aggregations/aggr_file_download/v6/aggr-file-download-v1.json, invenio_stats/contrib/aggregations/aggr_file_download/v7/aggr-file-download-v1.json, invenio_stats/contrib/aggregations/aggr_record_view/v2/aggr-record-view-v1.json, invenio_stats/contrib/aggregations/aggr_record_view/v5/aggr-record-view-v1.json, invenio_stats/contrib/aggregations/aggr_record_view/v6/aggr-record-view-v1.json, invenio_stats/contrib/aggregations/aggr_record_view/v7/aggr-record-view-v1.json, invenio_stats/contrib/file_download/v5/file-download-v1.json, invenio_stats/contrib/file_download/v6/file-download-v1.json, invenio_stats/contrib/file_download/v7/file-download-v1.json, invenio_stats/contrib/record_view/v5/record-view-v1.json, invenio_stats/contrib/record_view/v6/record-view-v1.json, invenio_stats/contrib/record_view/v7/record-view-v1.json, invenio_stats/contrib/registrations.py, invenio_stats/processors.py, invenio_stats/queries.py, invenio_stats/tasks.py, invenio_stats/utils.py, setup.py, tests/conftest.py, tests/test_aggregations.py, tests/test_cli.py, tests/test_processors.py
* address #81
* bucket size: get the buckets cardinality and use it as the bucket size
* move the bookmark to a separate index
* add ES 7 mappings
* add ES 7 tests on Travis
* change doctype accordingly with ES version
* fix mappings of es5 and es6
=> Es upgrade

examples/app.py, invenio_stats/aggregations.py, invenio_stats/contrib/aggregations/aggr_file_download/v2/aggr-file-download-v1.json, invenio_stats/contrib/aggregations/aggr_file_download/v5/aggr-file-download-v1.json, invenio_stats/contrib/aggregations/aggr_file_download/v6/aggr-file-download-v1.json, invenio_stats/contrib/aggregations/aggr_file_download/v7/aggr-file-download-v1.json, invenio_stats/contrib/aggregations/aggr_record_view/v2/aggr-record-view-v1.json, invenio_stats/contrib/aggregations/aggr_record_view/v5/aggr-record-view-v1.json, invenio_stats/contrib/aggregations/aggr_record_view/v6/aggr-record-view-v1.json, invenio_stats/contrib/aggregations/aggr_record_view/v7/aggr-record-view-v1.json, invenio_stats/contrib/file_download/v2/file-download-v1.json, invenio_stats/contrib/file_download/v5/file-download-v1.json, invenio_stats/contrib/file_download/v6/file-download-v1.json, invenio_stats/contrib/file_download/v7/file-download-v1.json, invenio_stats/contrib/record_view/v2/record-view-v1.json, invenio_stats/contrib/record_view/v5/record-view-v1.json, invenio_stats/contrib/record_view/v6/record-view-v1.json, invenio_stats/contrib/record_view/v7/record-view-v1.json, invenio_stats/ext.py, invenio_stats/processors.py, invenio_stats/queries.py, tests/conftest.py, tests/test_prefixing.py
=> global: indices prefix support

.travis.yml
Bump Elasticsearch version as requested in inveniosoftware/invenio#3961.
=> travis: bump Elasticsearch version

.github/workflows/tests.yml, invenio_stats/aggregations.py, invenio_stats/queries.py, tests/conftest.py, tests/helpers.py, tests/test_aggregations.py, tests/test_cli.py, tests/test_prefixing.py
=> Aggregations scalability improvements

CHANGES.rst, invenio_stats/version.py
tests suite was not run for these commits, needs to be tested
the changes were tested in local instance installation (invenio-app-ils)
=> release: v2.0.0

invenio_stats/aggregations.py
This should be cherry picked for v3 as well
=> aggreagations: fix bug on list bookmarks

invenio_stats/processors.py, tests/test_cli.py, tests/test_prefixing.py, tests/test_processors.py
Closes https://github.com/zenodo/zenodo-rdm/issues/555
=> events: Set a month as the default index for the events

invenio_stats/aggregations.py, invenio_stats/bookmark.py, invenio_stats/contrib/aggregations/aggr_file_download/os-v1/aggr-file-download-v1.json, invenio_stats/contrib/aggregations/aggr_file_download/os-v2/aggr-file-download-v1.json, invenio_stats/contrib/aggregations/aggr_file_download/v7/aggr-file-download-v1.json, invenio_stats/contrib/aggregations/aggr_record_view/os-v1/aggr-record-view-v1.json, invenio_stats/contrib/aggregations/aggr_record_view/os-v2/aggr-record-view-v1.json, invenio_stats/contrib/aggregations/aggr_record_view/v7/aggr-record-view-v1.json, invenio_stats/contrib/file_download/os-v1/file-download-v1.json, invenio_stats/contrib/file_download/os-v2/file-download-v1.json, invenio_stats/contrib/file_download/v7/file-download-v1.json, invenio_stats/contrib/record_view/os-v1/record-view-v1.json, invenio_stats/contrib/record_view/os-v2/record-view-v1.json, invenio_stats/contrib/record_view/v7/record-view-v1.json, invenio_stats/processors.py, invenio_stats/tasks.py, invenio_stats/utils.py, tests/test_aggregations.py, tests/test_cli.py, tests/test_processors.py
This addresses https://github.com/zenodo/rdm-project/issues/203
It requires changes in three modules.
Stats: create a new index keeping track of the statistics that have been recalculated
Rdm-record: create a new task that reindexes all the documents identified in the previous step
invenio-app-rdm: Define the task
Please, let me know it things should be moved around
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By …
=> stats: Reindex documents after the statistics have been calculated

.github/workflows/pypi-publish.yml, CHANGES.rst, invenio_stats/__init__.py, setup.cfg
- setup: pin dependencies
- setup: change to reusable workflows
- release: v4.2.1
=> pin dependencies

invenio_stats/aggregations.py, invenio_stats/bookmark.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/256
=> aggregations: add yearly interval

.github/workflows/i18n-pull.yml, .github/workflows/i18n-push.yml, .tx/config, MANIFEST.in, babel.ini, invenio_stats/errors.py, invenio_stats/translations/en/LC_MESSAGES/messages.po, invenio_stats/translations/messages.pot, invenio_stats/views.py, setup.cfg, tests/test_aggregations.py, tests/test_processors.py
> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
=> I18n: Mark Missing Translations Backport

.github/workflows/i18n-pull.yml, .github/workflows/i18n-push.yml, .github/workflows/tests.yml, .tx/config, MANIFEST.in, babel.ini, invenio_stats/translations/en/LC_MESSAGES/messages.po, invenio_stats/translations/messages.pot, setup.cfg
> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
=> I18n-add-missing-configs

CHANGES.rst, invenio_stats/__init__.py
> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
=> release: v4.4.0
