inveniosoftware/invenio-stats

docs/api.rst, examples/app.py, invenio_stats/config.py, invenio_stats/contrib/aggregations/aggr-file-download-v1.json, invenio_stats/contrib/aggregations/aggr-record-view-v1.json, invenio_stats/contrib/events.py, invenio_stats/contrib/file-download/file-download-v1.json, invenio_stats/contrib/record-view/record-view-v1.json, invenio_stats/ext.py, invenio_stats/indexer.py, invenio_stats/queues.py, invenio_stats/receivers.py, invenio_stats/tasks.py, invenio_stats/templates.py, requirements-devel.txt, setup.py, tests/conftest.py, tests/test_invenio_stats.py
- ADDS aggregation classes for processing event data within specified time
frames
- ADDS templates for the monthly aggregation indices
=> WIP tasks: aggregations

invenio_stats/errors.py, invenio_stats/indexer.py, invenio_stats/tasks.py, tests/test_invenio_stats.py
* FIXES the querying in the aggregation tasks to use elasticsearch
date range, and aggregate over yearly, monthly or daily intervals
=> global: ES refactoring in aggregations 

examples/app.py, invenio_stats/errors.py, invenio_stats/tasks.py, tests/conftest.py, tests/test_invenio_stats.py
* ADDS test adding new events within interval, to assert 
that the aggregation will overwrite previous results.
* ADDS fixtures in conftest for creating events with different dates.
(Hardcoded to 10k events per given day for now).
=>  tests: overwrite previous aggregations

invenio_stats/contrib/queries.py
* Fixes missing start_date and end_date bug in the file-download
query.
* Fixes extract_date for python 2.
=> global: fix query bugs

invenio_stats/contrib/event_builders.py, invenio_stats/processors.py, tests/conftest.py, tests/test_aggregations.py, tests/test_events.py, tests/test_tasks.py
* ADD custom event _id field, which includes the timestamp,
object id and visitor id so that events occuring within a
specified time window are only counted once.
=> global: addition of event id

invenio_stats/processors.py, tests/test_events.py, tests/test_tasks.py
* ADD hashing of visitor id and unique id of an event to
shorten its _id field
=> processors: hash _id field

invenio_stats/processors.py, setup.py
* Fixes event indexing by removing microseconds from the timestamp.
=> global: fix timestamp in event indexing

.travis.yml, invenio_stats/contrib/aggregations/aggr-file-download/aggr-file-download-v1.json, invenio_stats/contrib/file-download/file-download-v1.json, tests/test_aggregations.py
* Fixes a bug appearing with elasticsearch 2.2 (closes #39).
=> global: fix elasticsearch 2.2 timestamp conflict

invenio_stats/processors.py, invenio_stats/receivers.py, setup.py
* Specifies the Flask application as the signal sender to avoid double
publishing of events. (closes #50)
=> receivers: specify app as signal sender

setup.py
* add invenio-celery as dependency
* invenio-celery 1.1.1 pins celery to be less than 4.3 because of a bug
with msgpack serialization. This triggers a pip conflict when
installing kombu
=> global: pin kombu dependency

CHANGES.rst, invenio_stats/version.py, setup.py
* removes the kombu pinned version
=> global: bump invenio-celery version

.travis.yml, CHANGES.rst, invenio_stats/version.py, requirements-devel.txt, setup.py, tests/conftest.py, tests/contrib/test_event_builders.py, tests/test_aggregations.py, tests/test_processors.py, tests/test_utils.py
- updated travis and deps according to https://codimd.web.cern.ch/ZQl86wwkTp2ev_qmQXWyzQ?both
- replaced mock with standard library
=> global: travis and invenio-base depencencies

CHANGES.rst, invenio_stats/version.py, invenio_stats/views.py, pytest.ini, run-tests.sh
- fix isort arguments
- filter pytest deprecation warnings
- default 0 value instead of None
- closes #111
=> views: return sensible defaults instead of None

README.rst, docs/overview.rst, examples/app-setup.sh, examples/app.py, invenio_stats/__init__.py, invenio_stats/aggregations.py, invenio_stats/contrib/config.py, invenio_stats/processors.py, invenio_stats/queries.py, tests/conftest.py, tests/test_aggregations.py, tests/test_cli.py, tests/test_prefixing.py, tests/test_processors.py, tests/test_queries.py, tests/test_tasks.py
Because we're not exclusively using Elasticsearch anymore (in fact, the default nowadays is OpenSearch), only referring to Elasticsearch when we're talking about search engines is incorrect.
This PR remedies this issue.
=> Replace references to Elasticsearch

invenio_stats/aggregations.py, invenio_stats/ext.py, invenio_stats/utils.py, invenio_stats/views.py, tests/test_invenio_stats.py
This introduces a centralized builder function for `query` objects that caches results to save a few constructors, similar to the `extension.get_event_emitter()`.
=> Add cached builder function for query objects

invenio_stats/aggregations.py
This issue was introduced by [this commit](https://github.com/inveniosoftware/invenio-stats/commit/e92f86a1bc663a68543863a7577a95630b6f16b1#diff-950fc8b8e89bc3d7d726a3377df3a17d77a5b31664bc59f0cf47cf65f3828664R269). However, the new function `_split_date_range` is not used, and it looks like very much related.
The fix is probably different (should use `_split_date_range`), but I wait for instructions from the creator.
=> agg: fix wrong method params

invenio_stats/aggregations.py
This PR cherry-picks some minor updates from the [closed "bucket aggregations" PR](https://github.com/inveniosoftware/invenio-stats/pull/130).
Nothing dramatic, just nice-to-haves.
=> Minor updates

setup.cfg, tests/conftest.py
Invenio-Accounts v2.1.0 brings in the Invenio-i18n dependency, which is actually needed by newer invenio-accounts versions
=> Bump invenio-accounts dependency

invenio_stats/aggregations.py, tests/test_aggregations.py
Ensures that a second aggregation does not reprocess any aggregation already performed and that has not changed,
It addresses https://github.com/zenodo/rdm-project/issues/523
* closes https://github.com/zenodo/rdm-project/issues/523
=> stats: Ensure that events are aggregated only once

.github/actions/pre-install/action.yml, .github/workflows/tests.yml, CHANGES.rst, invenio_stats/__init__.py, invenio_stats/config.py, invenio_stats/templates.py, setup.cfg
> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
2. You agree that you have the right to license …
=> global: add support for index templates

CHANGES.rst, invenio_stats/__init__.py, setup.cfg, tests/conftest.py, tests/test_views.py
- setup: bump major dependencies
- release: v5.0.0
=> bump major

invenio_stats/errors.py, invenio_stats/views.py, tests/test_aggregations.py
There are untranslated permission and usage errors in views.py and errors.py. 
This PR fixes those by using `gettext` from invenio-i18n.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder** …
=> i18n: Fix untranslated strings in views and errors
